//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesWorkforce.MobileApp.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesWorkforce.MobileApp.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Acquire Current Location Address..
        /// </summary>
        public static string Error_CantAcquireCurrentLocationAddress {
            get {
                return ResourceManager.GetString("Error_CantAcquireCurrentLocationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Acquire Selected Location Address..
        /// </summary>
        public static string Error_CantAcquireSelectedLocationLocationAddress {
            get {
                return ResourceManager.GetString("Error_CantAcquireSelectedLocationLocationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occured..
        /// </summary>
        public static string Error_DefaultServerError {
            get {
                return ResourceManager.GetString("Error_DefaultServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that Wi-Fi or mobile data is turned on then try again..
        /// </summary>
        public static string Error_NoInternetConnectivity {
            get {
                return ResourceManager.GetString("Error_NoInternetConnectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we&apos;re having trouble with our server..
        /// </summary>
        public static string Error_ServerErrror {
            get {
                return ResourceManager.GetString("Error_ServerErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please login again to continue..
        /// </summary>
        public static string Error_SessionExpireMessage {
            get {
                return ResourceManager.GetString("Error_SessionExpireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string Error_SessionExpireTitle {
            get {
                return ResourceManager.GetString("Error_SessionExpireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string LabelAccount {
            get {
                return ResourceManager.GetString("LabelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent ID.
        /// </summary>
        public static string LabelAgentId {
            get {
                return ResourceManager.GetString("LabelAgentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Code.
        /// </summary>
        public static string LabelBadgeCode {
            get {
                return ResourceManager.GetString("LabelBadgeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock In.
        /// </summary>
        public static string LabelClockIn {
            get {
                return ResourceManager.GetString("LabelClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Out.
        /// </summary>
        public static string LabelClockOut {
            get {
                return ResourceManager.GetString("LabelClockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string LabelCustomers {
            get {
                return ResourceManager.GetString("LabelCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string LabelEmailAddress {
            get {
                return ResourceManager.GetString("LabelEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geofencing.
        /// </summary>
        public static string LabelGeofencing {
            get {
                return ResourceManager.GetString("LabelGeofencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geotagging.
        /// </summary>
        public static string LabelGeotagging {
            get {
                return ResourceManager.GetString("LabelGeotagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LabelLocationName {
            get {
                return ResourceManager.GetString("LabelLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        public static string LabelLogTime {
            get {
                return ResourceManager.GetString("LabelLogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type.
        /// </summary>
        public static string LabelLogType {
            get {
                return ResourceManager.GetString("LabelLogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string LabelMenu {
            get {
                return ResourceManager.GetString("LabelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string LabelMiddleName {
            get {
                return ResourceManager.GetString("LabelMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string LabelNo {
            get {
                return ResourceManager.GetString("LabelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders.
        /// </summary>
        public static string LabelPurchaseOrders {
            get {
                return ResourceManager.GetString("LabelPurchaseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string LabelSignout {
            get {
                return ResourceManager.GetString("LabelSignout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to sign out?.
        /// </summary>
        public static string LabelSignoutMessage {
            get {
                return ResourceManager.GetString("LabelSignoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string LabelSignoutTitle {
            get {
                return ResourceManager.GetString("LabelSignoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully {0}..
        /// </summary>
        public static string LabelSuccessMessage {
            get {
                return ResourceManager.GetString("LabelSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is outside the geofence.
        /// </summary>
        public static string LabelVerifyLocationOutsideMessage {
            get {
                return ResourceManager.GetString("LabelVerifyLocationOutsideMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string LabelYes {
            get {
                return ResourceManager.GetString("LabelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching....
        /// </summary>
        public static string LoadingFetching {
            get {
                return ResourceManager.GetString("LoadingFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Current Location....
        /// </summary>
        public static string LoadingFetchingCurrentLocation {
            get {
                return ResourceManager.GetString("LoadingFetchingCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Selected Location Address....
        /// </summary>
        public static string LoadingFetchingSelectedLocationAddress {
            get {
                return ResourceManager.GetString("LoadingFetchingSelectedLocationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In....
        /// </summary>
        public static string LoadingLoggingIn {
            get {
                return ResourceManager.GetString("LoadingLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting.
        /// </summary>
        public static string LoadingSubmitting {
            get {
                return ResourceManager.GetString("LoadingSubmitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TitleAccount {
            get {
                return ResourceManager.GetString("TitleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Logs.
        /// </summary>
        public static string TitleAttendanceLogs {
            get {
                return ResourceManager.GetString("TitleAttendanceLogs", resourceCulture);
            }
        }
    }
}
